services:
  discuzq:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "18002:80"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: